import type { Metadata } from 'next'
import Link from 'next/link'
import { metadonneesPage } from '@/lib/site'
import s from '../partenariat.module.css'

export const metadata: Metadata = {
  ...metadonneesPage('/partenariat/donnees', 'Vos données de candidature partenaire — FOREAS', 'Responsable, utilisation, destinataires, conservation et droits pour votre candidature partenaire FOREAS Driver.'),
  robots: { index: false, follow: true },
}

export default function DonneesPartenariat() {
  return <main className={s.page}><article className={`${s.container} ${s.section} ${s.privacy}`}>
    <Link href="/partenariat#candidature" className={s.textLink}>Revenir à la candidature</Link>
    <p className={s.eyebrow}>PROGRAMME PARTENAIRE · 12 SEPTEMBRE 2026</p>
    <h1>Vos données,<br />pour étudier votre projet.</h1>
    <p>Cette notice concerne la candidature depuis la page /partenariat. Son envoi permet d’examiner votre activité et de vous répondre. Il ne vaut ni admission, ni inscription à une liste publicitaire.</p>
    <section><h2>Qui s’en occupe ?</h2><p>EPHIALTES, SIREN 940 879 281, 58 rue de Monceau, 75008 Paris, France, est responsable de ce traitement. Votre contact : <a href="mailto:contact@foreas.xyz">contact@foreas.xyz</a>.</p></section>
    <section><h2>Quelles informations ?</h2><p>Votre activité, votre structure ou nom professionnel, votre nom et votre email sont nécessaires pour examiner la demande. Sans ces informations, le formulaire ne peut pas être envoyé. Le téléphone et le message sont facultatifs. La date de candidature et son état sont enregistrés pour son suivi.</p><p>Les services techniques traitent aussi les informations de connexion nécessaires à leur fonctionnement et à leur sécurité. N’ajoutez aucun mot de passe, document bancaire, donnée sensible ou information privée d’un chauffeur dans votre message.</p></section>
    <section><h2>Pourquoi et sur quelle base ?</h2><p>Si vous candidatez pour vous-même, l’examen et la préparation de la collaboration répondent à votre demande avant un éventuel contrat. Si vous représentez une structure, EPHIALTES utilise vos coordonnées dans son intérêt légitime à étudier cette demande et à échanger avec son représentant.</p><p>La protection contre les abus et la conservation des éléments nécessaires à un désaccord reposent sur l’intérêt légitime de sécuriser le programme et de défendre les droits des parties. Le formulaire ne prend pas de décision d’admission automatique.</p></section>
    <section><h2>Qui les reçoit ?</h2><p>Les personnes habilitées d’EPHIALTES accèdent au dossier. Vercel héberge le site et traite l’envoi du formulaire. Supabase enregistre la candidature. Resend assure les courriels de confirmation et l’alerte à EPHIALTES lorsqu’un envoi est effectué. Les services de messagerie des destinataires reçoivent ces courriels.</p><p>Le circuit de candidature peut transmettre dans l’alerte interne la structure, le nom, l’email, le téléphone, l’activité et le message. La confirmation utilise l’email, le nom et la structure. Les informations ne sont pas communiquées à d’autres partenaires pour leur prospection.</p></section>
    <section><h2>Où sont-elles traitées ?</h2><p>Les prestataires peuvent faire intervenir des équipes ou des infrastructures hors de l’Espace économique européen. Leurs accords de traitement prévoient des garanties de transfert, notamment des clauses contractuelles types européennes dans les situations concernées : <a href="https://vercel.com/legal/dpa">Vercel</a>, <a href="https://supabase.com/legal/customer-resources/data-processing-addendum">Supabase</a> et <a href="https://resend.com/legal/dpa">Resend</a>. Vous pouvez demander à EPHIALTES des précisions et une copie des garanties applicables à votre dossier.</p></section>
    <section><h2>Combien de temps ?</h2><p>La candidature est conservée pendant son examen. En cas de refus, de retrait ou d’échange resté sans suite, le dossier et les copies de suivi détenues par EPHIALTES doivent être supprimés au plus tard six mois après la décision, le retrait ou le dernier échange. Une candidature restée ouverte ne justifie pas une conservation indéfinie.</p><p>En cas d’admission, seules les informations utiles rejoignent le dossier du partenariat. Les éléments nécessaires à un litige peuvent être conservés séparément pendant sa résolution et le délai applicable. Les sauvegardes et journaux techniques suivent les cycles d’expiration des prestataires ; ils sont pris en compte dans le traitement d’une demande d’effacement.</p></section>
    <section><h2>Vos droits</h2><p>Vous pouvez demander l’accès à vos données, leur rectification, leur effacement ou la limitation de leur utilisation. Vous pouvez vous opposer aux traitements fondés sur l’intérêt légitime et demander la portabilité lorsque ses conditions s’appliquent. Certaines obligations ou un litige peuvent limiter l’effacement ; la raison vous sera expliquée.</p><p>Écrivez à <a href="mailto:contact@foreas.xyz?subject=Donn%C3%A9es%20de%20candidature%20partenaire">contact@foreas.xyz</a>, depuis l’adresse de candidature si possible. N’envoyez pas spontanément de pièce d’identité. Vous pouvez aussi adresser une réclamation à la <a href="https://www.cnil.fr/fr/plaintes">CNIL</a>.</p><p>Envoyer votre candidature ne modifie pas vos choix de traceurs et n’autorise pas de nouvelles sollicitations sans rapport avec votre projet.</p></section>
    <Link href="/partenariat#candidature" className={s.cta}>Revenir à ma candidature</Link>
  </article></main>
}
